### ISSUE TITLE
Version Check Doesn't Work With Tensorflow v1.10.0

### ISSUE THREAD

**Issue by Shloosh** [tensorflow/hub#145]
I'm trying to convert a keras model to tensorflow.js.

To do this, I execute the following command in bash:
`tensorflowjs_converter --input_format model.h5 /tmp`

And get the following error w stacktrace:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/shloosh/anaconda3/bin/tensorflowjs_converter", line 7, in <module>
    from tensorflowjs.converters.converter import main
  File "/home/shloosh/anaconda3/lib/python3.6/site-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "/home/shloosh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/__init__.py", line 24, in <module>
    from tensorflowjs.converters.tf_saved_model_conversion import convert_tf_saved_model
  File "/home/shloosh/anaconda3/lib/python3.6/site-packages/tensorflowjs/converters/tf_saved_model_conversion.py", line 34, in <module>
    import tensorflow_hub as hub
  File "/home/shloosh/anaconda3/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 65, in <module>
    _check_tensorflow_version(tf.VERSION)
  File "/home/shloosh/anaconda3/lib/python3.6/site-packages/tensorflow_hub/__init__.py", line 62, in _check_tensorflow_version
    _NIGHTLY_VERSION, _MAIN_VERSION, version))
RuntimeError: TensorFlow Hub depends on 'tf-nightly' build after 20180308 or 'tensorflow~=1.7'. Found tf.VERSION = 1.10.0
```

We can check my tensorflow installed versions with pip freeze | grep tensorflow:
```
tensorflow==1.9.0
tensorflow-gpu==1.10.0
tensorflow-hub==0.1.0
tensorflowjs==0.5.7
```

So the system is using tensorflow-gpu 1.10.0 and is throwing an error in the _check_tensorflow_version method of tensorflow_hub/\_\_init\_\_.py . Let's take a look at that function:
```
_MAIN_VERSION = "1.7"
match = re.search("^([0-9]+.[0-9]+)", version)
if match:
  if match.group(1) >= _MAIN_VERSION:
    return
```

After some testing in the python interpreter, we can see that a match is being generated, but "1.10" is not >= "1.7" because the string comparison only sees "1.1" >= "1.7".

I recommend either using a version comparison library, or converting the minor version number to an integer for comparison.

**Comment by andresusanopinto** [comment]
This has been fixed in tensorflow-hub 0.1.1 please update.
