### ISSUE TITLE
hub.Module error on GPU

### ISSUE THREAD

**Issue by xieximing** [tensorflow/hub#169]
I import the tensorflow_hub but when I do this `detector=hub.Module("https://tfhub.dev/google/faster_rcnn/openimages_v4/inception_resnet_v2/1" )` I got an error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/xieximing/venv/lib/python2.7/site-packages/tensorflow_hub/module.py", line 105, in __init__
    self._spec = as_module_spec(spec)
  File "/data/xieximing/venv/lib/python2.7/site-packages/tensorflow_hub/module.py", line 31, in as_module_spec
    return native_module.load_module_spec(spec)
  File "/data/xieximing/venv/lib/python2.7/site-packages/tensorflow_hub/native_module.py", line 99, in load_module_spec
    path = compressed_module_resolver.get_default().get_module_path(path)
  File "/data/xieximing/venv/lib/python2.7/site-packages/tensorflow_hub/compressed_module_resolver.py", line 141, in get_default
    HttpCompressedFileResolver(),
  File "/data/xieximing/venv/lib/python2.7/site-packages/tensorflow_hub/compressed_module_resolver.py", line 74, in __init__
    self._cache_dir = resolver.tfhub_cache_dir(cache_dir, use_temp=True)
  File "/data/xieximing/venv/lib/python2.7/site-packages/tensorflow_hub/resolver.py", line 67, in tfhub_cache_dir
    os.getenv(_TFHUB_CACHE_DIR, "") or FLAGS["tfhub_cache_dir"].value or
TypeError: '_FlagValues' object has no attribute '__getitem__'

Any help?

**Comment by arnoegw** [comment]
This reminds me of issue https://github.com/tensorflow/hub/issues/123 ...

Are you sure you're really running tensorflow>=1.8.0? The _FlagValues class existed in TensorFlow versions up to and including 1.4, but was removed in [commit 2652704](https://github.com/tensorflow/tensorflow/commit/2652704b576adc16b4d735f651cea1024e88b72e#diff-92ab93112cecf0bbfb502800268d86f7).

**Comment by hgadig** [comment]
Closing this issue as it is in "awaiting response" status for more than a week. Feel free to add your comments and we will reopen. Thanks!
