### ISSUE TITLE
Why category_list has no image sometimes when run retrain.py

### ISSUE THREAD

**Issue by smoothdvd** [tensorflow/hub#173]
```
CRITICAL:tensorflow:Label samoyed placeholder 004 has no images in the category validation.
[]
Traceback (most recent call last):
  File "retrain.py", line 1316, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/alexgao/.pyenv/versions/3.6.5/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "retrain.py", line 1093, in main
    FLAGS.tfhub_module))
  File "retrain.py", line 520, in get_random_cached_bottlenecks
    image_dir, category)
  File "retrain.py", line 261, in get_image_path
    mod_index = index % len(category_list)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by andresusanopinto** [comment]
It is just as it says: label "samoyed placeholder 004" has no limages for the category "validation".
You will need to debug what are the contents you are feeding the example script and why it is happening.
