### ISSUE TITLE
InternalError: GPU sync failed

### ISSUE THREAD

**Issue by ameyyadav09** [tensorflow/hub#179]
```
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
K.set_session(sess)
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=False)
sess.run(tf.global_variables_initializer())
sess.run(tf.tables_initializer())

model = prepare_model()
noHistory = model.fit(x_train, ytrain, epochs = 8, verbose = 1, batch_size = 32)
```
my ```prepare_model``` method is called to get the compiled model built in keras with tensorflow in back-end . the model has additional LSTM layers. I use the ```elmo``` in my model at the beginning.

**Entire thing worked fine when I had ```trainable = True``` , after I set it to False I am getting this error precisely after two epochs**, If I run the model on CPU irrespective of ```trainable``` flag it works fine. Can anybody tell me what is the issue here. 

I am using,
Windows 10,
Nvidia 1050 Ti
Python 3.5
tensorflow-gpu 1.11
Cuda 8

Below is the stack trace of my error.

Epoch 1/8
48128/48128 [==============================] - 1548s 32ms/step - loss: 3.0862 - acc: 0.4062 
Epoch 2/8
48128/48128 [==============================] - 1537s 32ms/step - loss: 1.4460 - acc: 0.6718
Epoch 3/8
26176/48128 [===============>..............] - ETA: 11:40 - loss: 1.0091 - acc: 0.7678Traceback (most recent call last):

  File "<ipython-input-3-6e2a5afb25f9>", line 5, in <module>
    batch_size = batch_size)

  File "C:\Users\demopc\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)

  File "C:\Users\demopc\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)

  File "C:\Users\demopc\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

  File "C:\Users\demopc\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)

  File "C:\Users\demopc\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1399, in __call__
    run_metadata_ptr)

  File "C:\Users\demopc\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))

InternalError: GPU sync failed

**Comment by xwzhong** [comment]
same issue, hope someone can explain

**Comment by ameyyadav09** [comment]
> 
> 
> same issue, hope someone can explain
@xwzhong  Did you try running it with lesser batch size.

**Comment by xwzhong** [comment]
@ameyyadav09 yes, i did, but it still occured. after that, I fix other bug, the "GPU sync failed" bug disappeared(running for 3day+), thanks much

**Comment by andresusanopinto** [comment]
This seems very unrelated with hub. Closing.

**Comment by sunnykalola73** [comment]
same problem ! please Help ...
