### ISSUE TITLE
Problem running retrain d\udc92acc\udce8s sp\udce9cifi\udce9 not found

### ISSUE THREAD

**Issue by soufianesabiri** [tensorflow/hub#245]
I'm trying to retrain using MobileNet v1 but when I run the command:
`python -m retrain --how_many_training_steps=500 --output_graph=out.pb --output_labels=labels.txt --image_dir=lp --tfhub_module https://tfhub.dev/google/imagenet/mobilenet_v1_100_224/feature_vector/1`

I get this error:
`WARNING: Logging before flag parsing goes to stderr.
W0304 13:35:01.532531  4928 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14
INFO:tensorflow:Looking for images in 'photos'
I0304 13:35:01.597208  4928 tf_logging.py:115] Looking for images in 'photos'
INFO:tensorflow:Looking for images in 'license'
I0304 13:35:01.658098  4928 tf_logging.py:115] Looking for images in 'license'
Traceback (most recent call last):
  File "C:\Users\Omen\Anaconda3\envs\tf\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Omen\Anaconda3\envs\tf\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Omen\Desktop\retrain.py", line 1313, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\Omen\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\Omen\Desktop\retrain.py", line 981, in main
    FLAGS.validation_percentage)
  File "C:\Users\Omen\Desktop\retrain.py", line 184, in create_image_lists
    file_list.extend(tf.gfile.Glob(file_glob))
  File "C:\Users\Omen\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 342, in get_matching_files
    for single_filename in filename
  File "C:\Users\Omen\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: C:/Users/Omen/Desktop/lp/license : Le chemin d\udc92acc\udce8s sp\udce9cifi\udce9 est introuvable.
; No such process`

Please help, thanks in advance!

**Comment by soufianesabiri** [comment]
I have put two folders and now it works... but the problem is I want the classifier to find only one type of images not two? Or should I include negative images???

**Comment by anis-13** [comment]
did you solve this probleme ?
