### ISSUE TITLE
Can not use with tf.contrib.distribute.CollectiveAllReduceStrategy

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/hub#268]
## Runtime

* tensorflow-hub: 0.3.0
* used on Google Cloud ML Engine
  * https://cloud.google.com/ml-engine/docs/scikit/runtime-version-list#1.13

## Summary

TensorFlow Hub does not work with `tf.contrib.distribute.CollectiveAllReduceStrategy`.
It results in the error below:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.5/site-packages/trainer/task.py", line 139, in <module>
    main()
  File "/root/.local/lib/python3.5/site-packages/trainer/task.py", line 135, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/training.py", line 462, in train_and_evaluate
    estimator, train_spec, eval_spec, _TrainingExecutor)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/estimator_training.py", line 289, in train_and_evaluate
    session_config=run_config.session_config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_coordinator.py", line 823, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_coordinator.py", line 359, in _run_single_worker
    return worker_fn(strategy)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/estimator_training.py", line 251, in _worker_fn
    hooks=hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1122, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1185, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1254, in _actual_train_model_distributed
    self.config))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1199, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 641, in _call_for_each_replica
    return _call_for_each_replica(self._container_strategy(), fn, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 189, in _call_for_each_replica
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 183, in _call_for_each_replica
    **merge_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 704, in _distributed_apply
    for grad, var in grads_and_vars
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 706, in <listcomp>
    var, update, args=(grad,), group=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1316, in update
    return self._update(var, fn, args, kwargs, group)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 690, in _update
    assert isinstance(var, values.DistributedVariable)
AssertionError
```

I used TensorFlow Hub as

```python
# Build ResNet
module = hub.Module(
    'https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/1',
    trainable=True,  # it did not work
    tags={'train'}
)
x = module(x)
```

As far as I investigated, the cases below worked:

* It worked when I tried with `trainable=False`
* It worked when I tried with a network I implemented in scratch (without TensorFlow Hub)

**Comment by hgadig** [comment]
Could you please explain the steps followed and help us providing a code snippet to reproduce the error at our end. Thanks!

**Comment by hgadig** [comment]
Closing this issue as it is in "awaiting response" state for more than 3 days.
