### ISSUE TITLE
hub.KerasLayer not compatible with tf.distribute

### ISSUE THREAD

**Issue by galeone** [tensorflow/hub#295]
If I try to create a Keras Model using `hub.KerasLayer` it works correctly if the model definition **is not** inside a distribution strategy scope.

If the model definition, instead, is inside the strategy the following exception is raised:

```
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow_hub/keras_layer.py", line 98, in __init__
    self._func = module_v2.load(handle)
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow_hub/module_v2.py", line 80, in load
    return tf_v1.saved_model.load_v2(module_handle)
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 324, in load
    export_dir)
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 63, in __init__
    self._setup_functions_captures()
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 100, in _setup_functions_captures
    for node_id in proto.bound_inputs]
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 100, in <listcomp>
    for node_id in proto.bound_inputs]
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 117, in _get_tensor_from_node
    return obj.handle
  File "/data/pgaleone/env/lib/python3.6/site-packages/tensorflow/python/distribute/values.py", line 317, in __getattr__
    return getattr(self.get(), name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'handle'
```

Here's a minimum reproducible example:

```python
import tensorflow as tf
import tensorflow_hub as hub

strategy = tf.distribute.MirroredStrategy()

with strategy.scope():

    model = tf.keras.Sequential(
        [
            hub.KerasLayer(
                "https://tfhub.dev/google/tf2-preview/inception_v3/feature_vector/2",
                output_shape=[2048],
                trainable=True,
            )
        ]
    )
```

**Comment by akhorlin** [comment]
Tensorflow team is working on a fix for this issue. We will update the thread once the fix is available for testing.

**Comment by galeone** [comment]
Awesome, thank you for the update!

**Comment by galeone** [comment]
Any updates?

**Comment by arnoegw** [comment]
To my knowledge, MirroredStrategy should work with recent versions of all pieces involved. Please try

  * the TF2 SavedModel at https://tfhub.dev/google/imagenet/inception_v3/feature_vector/4
  * tensorflow-hub 0.7.0
  * tensorflow 2.1, or failing that, a recent tf-nightly

For TPUStrategy, you may have to use tf-nightly or the upcoming 2.2rc.

**Comment by jbbiskup** [comment]
Hello, 
Was this corrected for all models in the tensorflow-hub ? 
I have :
```python
print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.experimental.list_physical_devices("GPU") else "NOT AVAILABLE")
strategy = tf.distribute.MirroredStrategy( cross_device_ops=tf.distribute.ReductionToOneDevice())
print('Number of devices: {}'.format(strategy.num_replicas_in_sync))
```

>TF Version:  2.1.0
>Eager mode:  True
Hub version:  0.7.0
GPU is available
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
Number of devices: 2

```python
URL = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/2"

with strategy.scope(): 
    model = tf.keras.Sequential([
      hub.KerasLayer(URL, input_shape=(IMAGE_RES, IMAGE_RES, 3),trainable = False ),
      layers.Dense(num_classes, activation='softmax')
    ])
    
    model.compile(
      optimizer='adam', 
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy'])
```
and I'm still having 

```
...:     model.compile(
      optimizer='adam', 
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy'])
Traceback (most recent call last):

  File "<ipython-input-7-67ab2c1e8e47>", line 4, in <module>
    layers.Dense(num_classes, activation='softmax')

  File "C:\Users\jbbis\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\jbbis\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\sequential.py", line 116, in __init__
    self.add(layer)

  File "C:\Users\jbbis\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)

  File "C:\Users\jbbis\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\sequential.py", line 203, in add
    output_tensor = layer(self.outputs[0])

  File "C:\Users\jbbis\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 748, in __call__
    self._maybe_build(inputs)

  File "C:\Users\jbbis\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2116, in _maybe_build
    self.build(input_shapes)

  File "C:\Users\jbbis\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\layers\core.py", line 1101, in build
    raise ValueError('The last dimension of the inputs to `Dense` '

ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`. 

```

**Comment by willbattel** [comment]
I'm trying to use TPUStrategy with the Efficientnet-lite models on TFHub, using AI Platform runtime 2.3 (TF 2.3, Python 3.7).

```
tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
print("Device:", tpu.master())
tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
strategy = tf.distribute.TPUStrategy(tpu)
print("Number of replicas:", strategy.num_replicas_in_sync)

with strategy.scope() if strategy is not None else contextlib.nullcontext():
    model = tf.keras.Sequential([
        hub.KerasLayer('gs://path/to/efficientnet_lite2_feature-vector_2', trainable=False),
        tf.keras.layers.Dense(num_classes),
        tf.keras.layers.Softmax()
    ])
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=['accuracy'])

model.fit(...)
```

This yields the following error:
```
Traceback (most recent call last):
    File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 538, in compile
        self._validate_compile(optimizer, metrics, **kwargs)
    File \"/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py\", line 2512, in _validate_compile
        '  model.compile(...)' % (v, strategy))
    ValueError: Variable (<tf.Variable 'efficientnet-lite2/stem/conv2d/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=array([[[[(I removed this to save space)]]]], dtype=float32)>) was not created in the distribution strategy scope of (<tensorflow.python.distribute.tpu_strategy.TPUStrategyV2 object at 0x7fe10028fed0>). It is most likely due to not all layers or the model or optimizer being created outside the distribution strategy scope.
```

Is there something more I have to do to use the hub.KerasLayer inside a TPUStrategy?

Side note: I believe these models are still in TF1 SavedModel format, because they don't appear when the TF2 filter is applied on the TFHub website. The normal Efficientnet models, however, have been published in TF2 format. I don't know if this is matters or not, but I'm guessing not because I can train without issue if I don't use a distribution strategy.

**Comment by saberkun** [comment]
To my knowledge, the efficientnet lite modules are not SavedModel (https://tfhub.dev/tensorflow/efficientnet/lite4/classification/2). It cannot be loaded as hub.KerasLayer.

**Comment by willbattel** [comment]
> To my knowledge, the efficientnet lite modules are not SavedModel (https://tfhub.dev/tensorflow/efficientnet/lite4/classification/2). It cannot be loaded as hub.KerasLayer.

Right, the classification models are not. However, there are also feature vectors that I can successfully load in for training, it only fails when I use a distribution strategy. https://tfhub.dev/tensorflow/efficientnet/lite1/feature-vector/2

**Comment by arnoegw** [comment]
Hi @willbattel, I'm afraid the model format ([TF1 Hub Module](https://www.tensorflow.org/hub/tf1_hub_module) vs [TF2 SavedModel](https://www.tensorflow.org/hub/tf2_saved_model)) is the issue here, so a full solution would require EfficientNet Lite to be republished in the TF2 SavedModel format – but I haven't heard of any plans to that effect.

That said, since you're anyways not trying to fine-tune, training can be restricted to the linear classifier on top. Depending on the size of your dataset, maybe a single GPU is enough and a distribution strategy is not needed after all? You could also consider generating training data for the linear classifier in a separate step and train the classifier from that, but I admit that makes it a bit tedious to assemble the final model for export.

**Comment by arnoegw** [comment]
Closing this, because the original problem has been resolved as explained on Mar 10, 2020, and the remaining issue with efficientnet/lite is an inherent limitation.
