### ISSUE TITLE
Importing text_embedding_column hangs

### ISSUE THREAD

**Issue by radusqrt** [tensorflow/hub#353]
I import ```tensorflow_hub``` and then try to get a text_embedding column but it hangs for several minutes and when I interrupt it there's a lock issue.

```
>>> import tensorflow_hub
>>> embedded_text_feature_column = hub.text_embedding_column(
...     key="sentence", 
...     module_spec="https://tfhub.dev/google/nnlm-en-dim128/1")
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> import tensorflow_hub as hub
>>> embedded_text_feature_column = hub.text_embedding_column(
...     key="sentence", 
...     module_spec="https://tfhub.dev/google/nnlm-en-dim128/1")
^CTraceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/radusqrt/anaconda3/envs/gpu/lib/python3.7/site-packages/tensorflow_hub/feature_column.py", line 98, in text_embedding_column
    module_spec = module.as_module_spec(module_spec)
  File "/home/radusqrt/anaconda3/envs/gpu/lib/python3.7/site-packages/tensorflow_hub/module.py", line 36, in as_module_spec
    return load_module_spec(spec)
  File "/home/radusqrt/anaconda3/envs/gpu/lib/python3.7/site-packages/tensorflow_hub/module.py", line 60, in load_module_spec
    path = registry.resolver(path)
  File "/home/radusqrt/anaconda3/envs/gpu/lib/python3.7/site-packages/tensorflow_hub/registry.py", line 42, in __call__
    return impl(*args, **kwargs)
  File "/home/radusqrt/anaconda3/envs/gpu/lib/python3.7/site-packages/tensorflow_hub/compressed_module_resolver.py", line 103, in __call__
    self._lock_file_timeout_sec())
  File "/home/radusqrt/anaconda3/envs/gpu/lib/python3.7/site-packages/tensorflow_hub/resolver.py", line 392, in atomic_download
    _wait_for_lock_to_disappear(handle, lock_file, lock_file_timeout_sec)
  File "/home/radusqrt/anaconda3/envs/gpu/lib/python3.7/site-packages/tensorflow_hub/resolver.py", line 342, in _wait_for_lock_to_disappear
    time.sleep(5)
KeyboardInterrupt
>>>
```

Do you have any idea why this is happening or how to solve it?
This happens both on CPU and GPU environments.

**Comment by rmothukuru** [comment]
@radusqrt ,
I tried your code, both in my PC and in Google Colab (Both CPU and GPU). It took around 2 minutes but it executed successfully, after that.

Can you please provide:
1. Details about what platform you are using (operating system, architecture). 
2. Specifications of your CPU

If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by radusqrt** [comment]
I see that now it works again, but I am connected to a better wifi network.
Could it be because the embedding column is big and it might take a while on my home network? Do you know how big it is?
