### ISSUE TITLE
Error converting .pb model to .tflite

### ISSUE THREAD

**Issue by mohitranawat** [tensorflow/hub#371]
I have pytorch model I wanted to deploy model into android , so I save model in .onnx and then I convert it into .pb file.
But I am facing errors while converting .pb to .tflite
Tensorflow version - 1.13.1

`import tensorflow as tf

graph_def_file = "tensorf.pb"
input_arrays = ['Const']
output_arrays = ['concat_98']

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("tensorf_lite.tflite", "wb").write(tflite_model)`

Error log - 

`Traceback (most recent call last):
  File "tfliteconvertor.py", line 8, in <module>
    tflite_model = converter.convert()
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\lite\python\lite.py", line 455, in convert
    **converter_kwargs)
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 442, in toco_convert_impl
    input_data.SerializeToString())
  File "C:\Program Files\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 205, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-10-01 12:18:57.243087: I tensorflow/lite/toco/import_tensorflow.cc:1324] Converting unsupported operation: PyFunc
2019-10-01 12:18:57.243738: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-10-01 12:18:57.244227: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-10-01 12:18:57.244653: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-10-01 12:18:57.245022: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2019-10-01 12:18:57.245590: F tensorflow/lite/toco/import_tensorflow.cc:114] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)`

**Comment by rmothukuru** [comment]
@mohitranawat,
This issue is not related to Tensorflow Hub, but it is related to TF Lite. Request you to raise an issue in [Tensorflow Repository](https://github.com/tensorflow/tensorflow/issues/). It is because Experts related to Tensorflow and TF Lite look into the issues in that Repo. Thanks!

**Comment by mohitranawat** [comment]
@rmothukuru Thanks.
