### ISSUE TITLE
Issue when trying to Import tensorflow_hub

### ISSUE THREAD

**Issue by samarthsikand** [tensorflow/hub#535]
I am facing the below issue when trying to import tensorflow_hub in my Python env
OS: Windows 10
Python: 3.6
Tensorflow version: 1.12
Tensorflow_hub version: 0.7.0
```
>>> import tensorflow_hub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\derp\.conda\envs\new_tf_gpu\lib\site-packages\tensorflow_hub\__init__.py", line 53, in <module>
    from tensorflow_hub.keras_layer import KerasLayer
  File "C:\Users\derp\.conda\envs\new_tf_gpu\lib\site-packages\tensorflow_hub\keras_layer.py", line 34, in <module>
    from tensorflow.python.training.tracking import data_structures
  File "C:\Users\derp\.conda\envs\new_tf_gpu\lib\site-packages\tensorflow\python\training\tracking\data_structures.py", line 35, in <module>
    from tensorflow.python.saved_model import revived_types
  File "C:\Users\derp\.conda\envs\new_tf_gpu\lib\site-packages\tensorflow\python\saved_model\revived_types.py", line 22, in <module>
    from tensorflow.core.protobuf import saved_object_graph_pb2
  File "C:\Users\derp\.conda\envs\new_tf_gpu\lib\site-packages\tensorflow\core\protobuf\saved_object_graph_pb2.py", line 31, in <module>
    dependencies=[tensorflow_dot_core_dot_protobuf_dot_trackable__object__graph__pb2.DESCRIPTOR,tensorflow_dot_core_dot_protobuf_dot_struct__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_types__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_versions__pb2.DESCRIPTOR,tensorflow_dot_core_dot_framework_dot_variable__pb2.DESCRIPTOR,])
  File "C:\Users\derp\.conda\envs\new_tf_gpu\lib\site-packages\google\protobuf\descriptor.py", line 884, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorflow/core/protobuf/saved_object_graph.proto":
  tensorflow.SavedVariable.synchronization: ".tensorflow.VariableSynchronization" is not defined.
  tensorflow.SavedVariable.aggregation: ".tensorflow.VariableAggregation" is not defined.
```

A comment in Issue #513 mentions that TF version 1.12 and above should work fine, but it doesn't seem to be the case. Any help would be appreciated. Thanks.

**Comment by khimraj** [comment]
@samarthsikand, I strongly recommend to use Tensorflow 1.15 or Tensorflow 2.x. And let me know if you face same issue again.

**Comment by gowthamkpr** [comment]
@samarthsikand I was able to import Tensorflow HUB 0.7 with Tensorflow 1.12 on google colab. As mentioned in the above comment I would also recommend you to use Tensorflow 1.15 ot Tensorflow 2.x and let me know if the issue still persists. Thanks!

**Comment by gowthamkpr** [comment]
@samarthsikand Can you please respond to the above comment so we can take this discussion further. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for 2 weeks. Please add additional comments to open this issue again. Thanks!

**Comment by jjhelmus** [comment]
Ran into a similar issue when updating the `tensorflow-hub` package in `conda-forge` (conda-forge/tensorflow-hub#10).  From my testing at least TensorFlow 1.14 is needed for TensorFlow-Hub 0.8.0.
