### ISSUE TITLE
RuntimeError: Can't copy Tensor with type string to device

### ISSUE THREAD

**Issue by karansaxena** [tensorflow/hub#562]
Hi,
I am using the example from the Universal Sentence Encoder https://tfhub.dev/google/universal-sentence-encoder-large/5 **on a GPU**.

**I am on TF 2.1.0 stable**

Traceback (most recent call last):
  File "create_sentence_embeddings.py", line 25, in <module>
    temp = embed(ele)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/saved_model/load.py", line 438, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 636, in _call
    *args, **kwds)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2185, in canonicalize_function_inputs
    self._flat_input_signature)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2240, in _convert_inputs_to_signature
    value, dtype_hint=spec.dtype)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1302, in convert_to_tensor
    value, dtype=preferred_dtype, name=name, as_ref=as_ref)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 317, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 258, in constant
    allow_broadcast=True)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 266, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/kasaxen/anaconda3/envs/qaenv/lib/python3.7/site-packages/tensorflow_core/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
RuntimeError: Can't copy Tensor with type string to device /job:localhost/replica:0/task:0/device:GPU:0.

**Comment by amahendrakar** [comment]
@karansaxena,

Could you please check [this comment](https://github.com/tensorflow/tensorflow/issues/38343#issuecomment-610853936) and let us know if it helps? 

Also, since the issue is being tracked in the TensorFlow repo, can we mark this as a duplicate and close this issue? Thanks!

**Comment by karansaxena** [comment]
Duplicate of https://github.com/tensorflow/tensorflow/issues/38343
