### ISSUE TITLE
USE model loading issue.

### ISSUE THREAD

**Issue by jaytimbadia** [tensorflow/hub#675]
This is the minimal application code
I have tried with both version of tensorflow, still giving same issue.

import tensorflow_hub as hub
import tensorflow as tf

g = tf.Graph()
with g.as_default():

text_input = tf.placeholder(dtype=tf.string, shape=[None])
embed = hub.Module("use_model")
embedded_text = embed(text_input)
init_op = tf.group([tf.global_variables_initializer(), tf.tables_initializer()])
g.finalize()

session = tf.Session(graph=g)
session.run(init_op)

result = session.run(embedded_text, feed_dict={text_input: ["Hello world"]})
print(result.shape)

Error:
Issues is when hub.Module runs,
I have downloaded https://tfhub.dev/google/universal-sentence-encoder-large/5 and extracted it in use_model folder.

so hub.Module('use_model') should load it, but giving ValueError mentioned above.

Traceback (most recent call last):
  File "endpoints.py", line 35, in <module>
    embed = hub.Module("use_model")
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\module.py", line 159, in __init__
    self._spec = as_module_spec(spec)
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\module.py", line 36, in as_module_spec
    return load_module_spec(spec)
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\module.py", line 69, in load_module_spec
    return registry.loader(path)
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\registry.py", line 44, in __call__
    return impl(*args, **kwargs)
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\native_module.py", line 154, in __call__
    return self._module_def_proto_to_module_spec(path)
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\native_module.py", line 139, in _module_def_proto_to_module_spec
    return _ModuleSpec(saved_model_handler, checkpoint_filename)
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\native_module.py", line 344, in __init__
    saved_model_handler, _SUPPORTED_COLLECTIONS)
  File "C:\Users\jay.timbadia\melon\lib\site-packages\tensorflow_hub\native_module.py", line 829, in check_collections_are_supported
    " as appropriate." % list(unsupported))
ValueError: Unsupported collections in graph: ['saved_model_main_op']
Use hub.create_module_spec(..., drop_collections=[...]) as appropriate.

Can anyone suggest?

**Comment by rmothukuru** [comment]
@jaytimbadia,
Reason for the error may be the version incomb[USE-5](https://tfhub.dev/google/universal-sentence-encoder-large/5) is trained on `Tensorflow Version 2.x` and you are using `Tensorflow Version 1.x` (understood from `Graphs` and `Placeholders`). Can you please upgrade your `Tensorflow to latest version (2.4)` and let us know how it goes. Thanks!

**Comment by jaytimbadia** [comment]
Yeah @rmothukuru, it was version issue, but I tried both the version earlier, it did not worked, but I guess I was trying with wrong functions.
It is working now. Thanks! Good to close.

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved.
