### ISSUE TITLE
Universal Sentence Encoder stops working after a while inside a Flask Docker

### ISSUE THREAD

**Issue by sainimohit23** [tensorflow/hub#708]
Hi, I am using Universal Sentence Encoder for the task of sentence similarity. So, I have built the following class and it is used by one of our Flask services to get similar sentences. 

```
class SimilarityModel():
    def __init__(self, df, working_directory):
        print("Loading model from tf hub...")
        self.model = hub.load(os.path.join(working_directory, module_path))
        # self.model = hub.load(module_url)
        self.currencies = currencies
        print ("module %s loaded" % module_url)
        
        self.df=df
        self.data_vectors=np.zeros( (len(df), 512), dtype="float32")
        for  i in range (len(self.df)):
            rep_vector=np.zeros((300,),dtype="float32")
            sentence=self.df['Rule'][i].lower()
            print(sentence)
            processed_sentence = self.process_text(sentence)
            self.data_vectors[i] = self.model([processed_sentence])
            
    # TODO: number + text
    def process_text(self, text):
        text = text.replace("/", " ").replace("-", " ").replace(".","")
        text =  text.strip().strip('.').split()
        temp_list = []
        for word in text:
            word = word.lower()
            if word.replace('.','').isdigit():
                temp_list.append('1000')
            elif word in self.currencies:
                temp_list.append('cur')
            else:
                temp_list.append(word)

        return " ".join(temp_list)

    def kneighbors(self, sentence, n_neighbors):
        processed_sent = [self.process_text(sentence)]
        sent_vector = self.model(processed_sent)
    
        similarities = cdist(sent_vector, self.data_vectors, metric='cosine')
        similarities = similarities[0]
        top_matches_idx = similarities.argsort()[:n_neighbors]
        return similarities[top_matches_idx][np.newaxis, ...], top_matches_idx[np.newaxis, ...]
```
Here df is the pandas dataframe that has some sentences. I am caching the encoding of these sentences to calculate the similarity with the query text in kneighbors().

When I start the application it just works file. But after some time it starts throwing the following error:

```
Traceback (most recent call last):
  File "/home/yatra/extract_rules_new.py", line 496, in extract_rules
    all_sentences, dict_of_sentences, messages_dict=get_sents_general(rules, matcher, similarity_model, airline_code)
  File "/home/yatra/extract_rules_new.py", line 255, in get_sents_general
    dist_list, dist_list_common = get_messages(temp_list, similarity_model, airline_code, key, dist_list_common)
  File "/home/yatra/extract_rules_new.py", line 71, in get_messages
    dist, indices = similarity_model.kneighbors(complete_sentence, n_neighbors=4) # Find closest 4 messages.
  File "/home/yatra/similarityModel.py", line 53, in kneighbors
    sent_vector = self.model(processed_sent)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/saved_model/load.py", line 509, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [1,512] vs. [0]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/l2_normalize}}]] [Op:__inference_restored_function_body_5647]

Function call stack:
restored_function_body

 Incompatible shapes: [1,512] vs. [0]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/l2_normalize}}]] [Op:__inference_restored_function_body_5647]

Function call stack:
restored_function_body

```

I have no idea why this is happening.

**Comment by rmothukuru** [comment]
@sainimohit23,
Can you try using [Tensorflow Serving](https://www.tensorflow.org/tfx/serving/docker) instead of Flask and let us know how it goes? Thanks!

**Comment by rmothukuru** [comment]
@sainimohit23,
Can you please respond to the above comment. Thanks!

**Comment by sainimohit23** [comment]
Hi @rmothukuru, I have to make changes in other codes/APIs for this. So, it will take some time.

**Comment by sainimohit23** [comment]
Hi, @rmothukuru can you please tell me what is the format of JSON input to the API? I found the following example on stackoverflow and it does not work.

> curl -d '{"inputs": {"text": ["Hello"]}}' -X POST http://localhost:8501/v1/models/model:predict

output:
```
{
    "error": "Missing named input: inputs in 'inputs' object."
}
```

Can you also tell me where to look for further reference regarding the API?

**Comment by rmothukuru** [comment]
@sainimohit23,
Can you please share the SignatureDef of your Model by running the Command, 

**`saved_model_cli show --dir /tmp/saved_model_dir --all`** .

Please refer [this documentation](https://www.tensorflow.org/guide/saved_model#show_command) for more details. 

Also, please refer this [Serving Documentation](https://www.tensorflow.org/tfx/serving/docker) to understand how to perform Inference. Thanks!

**Comment by sainimohit23** [comment]
HI @rmothukuru, sorry for the late reply. Here is the output of the above command.

```
2021-01-13 12:16:31.217374: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-01-13 12:16:31.217407: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_inputs:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['outputs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 512)
        name: StatefulPartitionedCall_1:0
  Method name is: tensorflow/serving/predict
2021-01-13 12:16:34.580190: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-01-13 12:16:34.580218: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-01-13 12:16:34.580241: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (lap0002594): /proc/driver/nvidia/version does not exist

Defined Functions:
  Function Name: '__call__'
    Option #1
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=<unknown>, dtype=tf.string, name='inputs')

  Function Name: 'predict'
    Option #1
      Callable with:
        Argument #1
          inputs
```

**Comment by WGierke** [comment]
Hi @sainimohit23 
Could you log the value of `processed_sent` in
```python
  File "/home/yatra/similarityModel.py", line 53, in kneighbors
    sent_vector = self.model(processed_sent)
```
and check for which value the process dies? The error message `Incompatible shapes: [1,512] vs. [0]` might point to some ill-formed input.

**Comment by sainimohit23** [comment]
Hi @WGierke, Actually I have a script scheduled in crontab that hits the API with the same input. So, the problem was not related to the input. I think it has something to do with resource management and the other dependencies of the program. So, I made another flask API with 2 workers and 10 threads, just to encode sentences and it is working fine. No problems since then.

Now I have another doubt. Do threads lock the usage of the model while predicting or do they predict concurrently? If former is the case then I should run more workers with 1 thread.

**Comment by akhorlin** [comment]
The locking in this case shouldn't present a bottleneck in this case. That being said, TF Hub doesn't provide any explicit thread-safety or locking guarantees, so going with 1 worker/1 thread or using Tensorflow Serving would be a more robust approach.
