### ISSUE TITLE
Lock file being created even when model had already been downloaded

### ISSUE THREAD

**Issue by clippered** [tensorflow/hub#744]
To reproduce in Linux:
1. Run this code as `root` user
```
>>> import tensorflow_hub as hub
>>> embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual/3")
```
2. Switch to a non-root user and run the same thing:
```
>>> import tensorflow_hub as hub
>>> embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual/3")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lang/lib/python3.8/site-packages/tensorflow_hub/module_v2.py", line 92, in load
    module_path = resolve(handle)
  File "/var/lang/lib/python3.8/site-packages/tensorflow_hub/module_v2.py", line 47, in resolve
    return registry.resolver(handle)
  File "/var/lang/lib/python3.8/site-packages/tensorflow_hub/registry.py", line 51, in __call__
    return impl(*args, **kwargs)
  File "/var/lang/lib/python3.8/site-packages/tensorflow_hub/compressed_module_resolver.py", line 67, in __call__
    return resolver.atomic_download(handle, download, module_dir,
  File "/var/lang/lib/python3.8/site-packages/tensorflow_hub/resolver.py", line 370, in atomic_download
    tf_utils.atomic_write_string_to_file(lock_file, lock_contents,
  File "/var/lang/lib/python3.8/site-packages/tensorflow_hub/tf_utils.py", line 65, in atomic_write_string_to_file
    f.write(contents)
  File "/var/lang/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 102, in write
    self._prewrite_check()
  File "/var/lang/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 87, in _prewrite_check
    self._writable_file = _pywrap_file_io.WritableFile(
tensorflow.python.framework.errors_impl.PermissionDeniedError: /opt/tfhub_modules/26c892ffbc8d7b032f5a95f316e2841ed4f1608c.lock.tmp92234c62ea7b4a1c95216654d6db1a83; Permission denied
```
The non-root user can still read the folder `/opt/tfhub_modules` and the files/folders in it. It just does not have write permissions.
This use case would be handy for baking images to be run in AWS Lambda which has a read-only filesystem

**Comment by akhorlin** [comment]
Hi Ken,

We will look into this issue. Meanwhile, one potential work-around is to set the env var to enable [uncompressed model resolution](https://www.tensorflow.org/hub/caching#reading_from_remote_storage).

TFHUB_MODEL_LOAD_FORMAT=UNCOMPRESSED

**Comment by akhorlin** [comment]
The fix has been submitted in https://github.com/tensorflow/hub/commit/bc9589114edc88ba662ef54992fed0a197042368. It will pushed to pypi package in the next scheduled release.

**Comment by clippered** [comment]
Amazing, thanks for the quick fix @akhorlin !
