### ISSUE TITLE
assets/vocab.txt; No such file or directory when loading/saving BERT encoder models

### ISSUE THREAD

**Issue by sfvaroglu** [tensorflow/hub#822]
The BERT encoder models from https://tfhub.dev/google/collections/bert/1 are failing with the error below:

```
Traceback (most recent call last):
  File "/home/tensorflow/test_load_save.py", line 32, in <module>
    tf.saved_model.save(model, model_path)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1280, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1327, in save_and_return_nodes
    builder_impl.copy_assets_to_destination_dir(asset_info.asset_filename_map,
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/saved_model/builder_impl.py", line 781, in copy_assets_to_destination_dir
    file_io.copy(asset_source_filepath, asset_destination_filepath)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 589, in copy
    copy_v2(oldpath, newpath, overwrite)
  File "/home/tensorflow/.venv_tf27/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 583, in copy_v2
    _pywrap_file_io.CopyFile(
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/tmp1ss70moo/assets/vocab.txt; No such file or directory
```

To reproduce:
```
model_name = "./models/bert_en_uncased_L-12_H-768_A-12_4.tar.gz"

if tarfile.is_tarfile(model_name):
    with tempfile.TemporaryDirectory() as td:
        with tarfile.open(model_name, "r") as tar:
            tar.extractall(path=td)
        model = tf.saved_model.load(td)

with tempfile.TemporaryDirectory() as td:
    model_path = os.path.join(td, "saved_model")
    tf.saved_model.save(model, model_path)
```

**Comment by WGierke** [comment]
This behavior is not specific to models from that collection but to all TF SavedModels that have assets. When you save them, you have to make sure that you also add the Asset that should be tracked. I adapted your example like so:

```python
!wget https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4?tf-hub-format=compressed -O model.tar.gz
!pip install tensorflow-text

import tempfile
import os
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text
import tarfile

model_name = "model.tar.gz"

if tarfile.is_tarfile(model_name):
    with tempfile.TemporaryDirectory() as td:
        with tarfile.open(model_name, "r") as tar:
            tar.extractall(path=td)
        model = tf.saved_model.load(td)
        # Attach the asset (https://www.tensorflow.org/api_docs/python/tf/saved_model/Asset)
        filename = tf.saved_model.Asset(td + "/assets/vocab.txt")
        @tf.function(input_signature=[])
        def func():
          return tf.io.read_file(filename)
        model.func = func
        tf.saved_model.save(model, "/tmp/saved_model")

text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
encoder_inputs = preprocessor(text_input)
outputs = hub.KerasLayer("/tmp/saved_model")(encoder_inputs)
pooled_output = outputs["pooled_output"] 
embedding_model = tf.keras.Model(text_input, pooled_output)
sentences = tf.constant(["(your text here)"])
print(embedding_model(sentences))

!mv /tmp/saved_model /tmp/new_location

outputs = hub.KerasLayer("/tmp/new_location")(encoder_inputs)
pooled_output = outputs["pooled_output"] 
embedding_model = tf.keras.Model(text_input, pooled_output)
sentences = tf.constant(["(your text here)"])
print(embedding_model(sentences))
```

**Comment by UsharaniPagadala** [comment]
@sfvaroglu 
Could you please confirm if this issue can be closed.Thanks!

**Comment by sfvaroglu** [comment]
Yes, thanks
