### ISSUE TITLE
Bug: BERT preprocess load error

### ISSUE THREAD

**Issue by Breezelled** [tensorflow/hub#882]
### What happened?

I'm trying to use the model from [https://tfhub.dev/tensorflow/bert_en_cased_preprocess/3](https://tfhub.dev/tensorflow/bert_en_cased_preprocess/3). While trying to train BERT.

### Relevant code

```python
def build_classifier_model():
    text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
    preprocessing_layer = hub.KerasLayer(tfhub_handle_preprocess, name='preprocessing')
    encoder_inputs = preprocessing_layer(text_input)
    encoder = hub.KerasLayer(tfhub_handle_encoder, trainable=True, name='BERT_encoder')
    outputs = encoder(encoder_inputs)
    net = outputs['pooled_output']
    net = tf.keras.layers.Dropout(0.1)(net)
    net = tf.keras.layers.Dense(1, activation=None, name='classifier')(net)
    return tf.keras.Model(text_input, net)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/breeze/.../model_train.py", line 11, in <module>
    classifier_model = bm.build_classifier_model()
  File "/Users/breeze/.../build_model.py", line 99, in build_classifier_model
    preprocessing_layer = hub.KerasLayer(tfhub_handle_preprocess, name='preprocessing')
  File "/Users/breeze/.../Miniconda/envs/dl/lib/python3.9/site-packages/tensorflow_hub/keras_layer.py", line 157, in __init__
    self._func = load_module(handle, tags, self._load_options)
  File "/Users/breeze/.../Miniconda/envs/dl/lib/python3.9/site-packages/tensorflow_hub/keras_layer.py", line 459, in load_module
    return module_v2.load(handle, tags=tags, options=set_load_options)
  File "/Users/breeze/.../Miniconda/envs/dl/lib/python3.9/site-packages/tensorflow_hub/module_v2.py", line 107, in load
    raise ValueError("Trying to load a model of incompatible/unknown type. "
ValueError: Trying to load a model of incompatible/unknown type. '/var/folders/79/mpnlph953xb8wrtccgd52c400000gn/T/tfhub_modules/b514e0625a489a1a48844d70f33193aec2816f05' contains neither 'saved_model.pb' nor 'saved_model.pbtxt'.
```

### tensorflow_hub Version

0.13.0.dev (unstable development build)

### TensorFlow Version

2.8 (latest stable release)

### Other libraries

tensorboard==2.12.1
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorflow-addons==0.20.0
tensorflow-datasets==4.9.0
tensorflow-estimator==2.12.0
tensorflow-hub==0.13.0
tensorflow-macos==2.12.0
tensorflow-metadata==1.13.0
tensorflow-metal==0.8.0
tensorflow-model-optimization==0.7.4
tensorflow-text==2.12.0

### Python Version

3.x

### OS

macOS

**Comment by Breezelled** [comment]
I trained and tested my code and model successfully in the previous days. But the error shows when I want to see the result today.

**Comment by singhniraj08** [comment]
@Breezelled,

I was able to run your model building function with below setup and it ran successfully. Please find [gist](https://colab.research.google.com/gist/singhniraj08/e36663f090e62e2052de5f83b62bcd9d/hub-882_bert_preprocess_load_error.ipynb) for reference.

Also, you can follow [bert guide](https://tfhub.dev/google/collections/bert/1) for compatible BERT preprocessing model and BERT encoder model. Please try running your code with below release versions and let us know if you face any challenges.
Thank you!


```
Tensorflow Version: 2.11.1
Tensorflow Hub Version: 0.13.0
Tensorflow Text Version: 2.11.0
```

**Comment by Breezelled** [comment]
Hi! I still can not run the model with the same error.
tfhub_handle_encoder: "https://tfhub.dev/tensorflow/bert_en_wwm_cased_L-24_H-1024_A-16/4"
tfhub_handle_preprocess:
"https://tfhub.dev/tensorflow/bert_en_cased_preprocess/3"
It's already follow the [bert guide](https://tfhub.dev/google/collections/bert/1) for compatible BERT preprocessing model and BERT encoder model.
However, I can train and test my model on my windows machine, but still can not run it on my M1 Max MacBook Pro
Here is the code and commend line output, These files output information is about the [Large Movie Review Dataset](https://ai.stanford.edu/~amaas/data/sentiment/), But I believe it not the reason regarding this error.
code:
```python
def build_classifier_model():
    text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
    preprocessing_layer = hub.KerasLayer(tfhub_handle_preprocess, name='preprocessing')
    encoder_inputs = preprocessing_layer(text_input)
    encoder = hub.KerasLayer(tfhub_handle_encoder, trainable=True, name='BERT_encoder')
    outputs = encoder(encoder_inputs)
    net = outputs['pooled_output']
    net = tf.keras.layers.Dropout(0.1)(net)
    net = tf.keras.layers.Dense(1, activation=None, name='classifier')(net)
    return tf.keras.Model(text_input, net)

print("Tensorflow Version:", tf.__version__)
print("Tensorflow Hub Version:", hub.__version__)
print("Tensorflow Text Version:", text.__version__)

bert_model = build_classifier_model()
print(bert_model.summary())
```
output:
```
Found 25000 files belonging to 2 classes.
Using 20000 files for training.
Metal device set to: Apple M1 Max

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

Found 25000 files belonging to 2 classes.
Using 5000 files for validation.
Found 25000 files belonging to 2 classes.
BERT model selected           : https://tfhub.dev/tensorflow/bert_en_wwm_cased_L-24_H-1024_A-16/4
Preprocess model auto-selected: https://tfhub.dev/tensorflow/bert_en_cased_preprocess/3
Tensorflow Version: 2.11.0
Tensorflow Hub Version: 0.13.0
Tensorflow Text Version: 2.11.0
Traceback (most recent call last):
  File "/Users/breeze/.../model_test.py", line 3, in <module>
    from build_model import build_classifier_model
  File "/Users/breeze/.../build_model.py", line 112, in <module>
    bert_model = build_classifier_model()
  File "/Users/breeze/.../build_model.py", line 99, in build_classifier_model
    preprocessing_layer = hub.KerasLayer(tfhub_handle_preprocess, name='preprocessing')
  File "/Users/breeze/.../Miniconda/envs/dl/lib/python3.9/site-packages/tensorflow_hub/keras_layer.py", line 157, in __init__
    self._func = load_module(handle, tags, self._load_options)
  File "/Users/breeze/.../Miniconda/envs/dl/lib/python3.9/site-packages/tensorflow_hub/keras_layer.py", line 459, in load_module
    return module_v2.load(handle, tags=tags, options=set_load_options)
  File "/Users/breeze/.../Miniconda/envs/dl/lib/python3.9/site-packages/tensorflow_hub/module_v2.py", line 107, in load
    raise ValueError("Trying to load a model of incompatible/unknown type. "
ValueError: Trying to load a model of incompatible/unknown type. '/var/folders/79/mpnlph953xb8wrtccgd52c400000gn/T/tfhub_modules/b514e0625a489a1a48844d70f33193aec2816f05' contains neither 'saved_model.pb' nor 'saved_model.pbtxt'.
```

**Comment by Breezelled** [comment]
I can reload the previous trained model and successfully get the test result, and I can deploy and use the previous trained model on tensorflow-serving in a Docker container as well. However, I am unable to test the model from hub on my M1 Max MacBook.
reload previous trained model:
```python
import tensorflow as tf
import tensorflow_text as text
from build_model import build_classifier_model
reloaded_model = tf.saved_model.load("models/imdb_bert_wwm_batch12_lr3e-5_epoch2")


def print_my_examples(inputs, results):
    result_for_printing = \
        [f'input: {inputs[i]:<30} : score: {results[i][0]:.6f}'
         for i in range(len(inputs))]
    print(*result_for_printing, sep='\n')
    print()


# classifier_model = build_classifier_model()

examples = [
    # pos
    "I'm surprised I never heard of this before. It had some really funny moments. The attack goats cracked me up.",
    "Because you'll probably be confused the first time around. It's not a coincidence it stars some of the greatest actors of our time.",
    'Superb, and truly one of the greatest movies of all time.It starts with the screenplay. Adapted from, and very faithful to, an excellent book. The book by Chuck Palahniuk was perfect for a movie: vivid, powerful, challenging, original, unpredictable. Considering how perfectly formed the book already was, the screenplay would have been a doddle.Some very interesting themes are explored - consumerism, class warfare, multiple-personality disorder, male bonding, terrorism and anarchy - without being judgemental. Direction is spot-on. Perfect cinematography, pacing and editing. The twists and nuances of the book are captured perfectly.Edward Norton and Brad Pitt are perfectly cast as the two lead characters, and deliver in spades. Helena Bonham Carter is a strange selection to take on the role of Marla, as she tends to act in Shakespearean dramas and other period pieces. However, despite this, her performance is very convincing.An absolute classic.',
    # neg
    "The film may have a satisfying ending, but the journey to getting there is a little tedious and annoying. It didn't engage me.",
    "This was not as good as the second by a long way. In fact it was bordering on boring. There wasn't enough violence, it moved too slowly and there wasn't enough dancing. It does complete the trilogy except the fourth one that Toxie mentions in this film. Worth making time for if you have seen the first two and want to finish the story. It is a deliberately bad movie.",
    "Chris Rock, who wrote and directed this film, can be very funny. However, this movie wanders all over the place, and when it doesn't work it can be really awful.Why throw in completely over-the-top, unfunny, and highly explicit sex scenes when they seem to come out of left field, and not really congruent with the rest of the story. I much preferred the chemistry between Rock and the superbly talented and beautiful Rosario Dawson, which, I thought, worked really well. Gabrielle Union, J. B. Smoove, and Leslie Jones also added well to the mix here.All in all, as mentioned, the movie is way too choppy, with some really cringe inducing scenes, and overall a disappointment.",
]

# sigmod将数值映射到0-1区间
reloaded_results = tf.sigmoid(reloaded_model(tf.constant(examples)))
# original_results = tf.sigmoid(classifier_model(tf.constant(examples)))

print('Results from the saved model:')
print_my_examples(examples, reloaded_results)
# print('Results from the model in memory:')
# print_my_examples(examples, original_results)
```

**Comment by Breezelled** [comment]
I can reload the previous trained model and successfully get the test result, and I can deploy and use the previous trained model on tensorflow-serving in a Docker container as well. However, I am unable to test the model from hub on my M1 Max MacBook.
reload previous trained model:
```python
import tensorflow as tf
import tensorflow_text as text
from build_model import build_classifier_model
reloaded_model = tf.saved_model.load("models/imdb_bert_wwm_batch12_lr3e-5_epoch2")


def print_my_examples(inputs, results):
    result_for_printing = \
        [f'input: {inputs[i]:<30} : score: {results[i][0]:.6f}'
         for i in range(len(inputs))]
    print(*result_for_printing, sep='\n')
    print()


# classifier_model = build_classifier_model()

examples = [
    "test sentence here.",
]

# sigmod mapping
reloaded_results = tf.sigmoid(reloaded_model(tf.constant(examples)))
# original_results = tf.sigmoid(classifier_model(tf.constant(examples)))

print('Results from the saved model:')
print_my_examples(examples, reloaded_results)
# print('Results from the model in memory:')
# print_my_examples(examples, original_results)
```

**Comment by singhniraj08** [comment]
@Breezelled,

Can you navigate to `'/var/folders/79/mpnlph953xb8wrtccgd52c400000gn/T/tfhub_modules/b514e0625a489a1a48844d70f33193aec2816f05'` directory on you Mac machine and check for the saved model files manually. TF-Hub creates a temp directory to save the loaded models. However, after a few days or so, the contents of the temp folders(the loaded model) will be deleted. When you try to load the model again, it will look in the same temp directory but the files would have been deleted.

The workaround is to delete the temp folder(in your case `b514e0625a489a1a48844d70f33193aec2816f05` folder) and run the code again. This will create a new directory to save model and load again later. The permanent solution is to download the model as `.tar` file and save it locally and provide the path while loading model.
Hope this helps. Thank you!

```
# download and save model in temp model and load model from temp folder on 2nd and so run
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")

# download and save model .tar file and load model by providing local path
bert_preprocess = hub.KerasLayer("<saved model path>/bert_en_uncased_preprocess_3.tar")
```

**Comment by Breezelled** [comment]
This really works! Thank you! I check the file and folders under this path, `'/var/folders/79/mpnlph953xb8wrtccgd52c400000gn/T/tfhub_modules/b514e0625a489a1a48844d70f33193aec2816f05'`. They are empty indeed. Then, I successfully run my test after deleting those empty folders under `'/var/folders/79/mpnlph953xb8wrtccgd52c400000gn/T/tfhub_modules'`.

**Comment by singhniraj08** [comment]
@Breezelled, Could you please close this issue if it's resolved. Thank you!
