### ISSUE TITLE
Bug: Getting CORS error while loading tensorflow-models/pose-detection, tensorflow-models/face-detection from today 

### ISSUE THREAD

**Issue by sourav-5exceptions** [tensorflow/hub#909]
### What happened?

Getting CORS error while loading tensorflow-models/pose-detection, tensorflow-models/face-detection from today

Access to fetch at 'https://www.kaggle.com/models/mediapipe/face-detection/frameworks/tfJs/variations/short/versions/1/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/mediapipe/tfjs-model/face_detection/short/1/model.json?tfjs-format=file') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Relevant code

```python
/* eslint-disable react-hooks/exhaustive-deps */
"use client";

import * as poseDetection from "@tensorflow-models/pose-detection";
import * as tf from "@tensorflow/tfjs-core";
import * as THREE from "three";

import React, { useEffect, useRef, useState } from "react";
import Webcam from "react-webcam";
// Register one of the TF.js backends.
import "@tensorflow/tfjs-backend-webgl";

  const loadPoseNet = async () => {
    try {
      setLoading(true);
      await tf.ready();

      //movenet configurations start

      // const detectorConfig = {
      //   // modelType: poseDetection.movenet.modelType.MULTIPOSE_LIGHTNING,
      //   modelType: poseDetection.movenet.modelType.SINGLEPOSE_LIGHTNING,
      //   enableSmoothing: true,
      //   // minPoseScore: 0.6,
      //   multiPoseMaxDimension: 352,
      // };

      // const net = await poseDetection.createDetector(
      //   poseDetection.SupportedModels.MoveNet,
      //   detectorConfig
      // );

      //movenet configurations end

      // blazenet configurations start

      // const detectorConfig = {
      //   runtime: "tfjs",
      //   enableSmoothing: true,
      //   modelType: "full",
      // };
      const detectorConfig = {
        runtime: "tfjs",
        modelType: "lite",
        enableSmoothing: true,
        inputWidth: 256,
        inputHeight: 256,
        quantBytes: 2, // Set to 4 for int32 quantization
        architecture: "ResNet", // Use 'MobileNet' or 'ResNet'
        scoreThreshold: 0.5, // Minimum confidence score for detected keypoints
      };

      const net = await poseDetection.createDetector(
        poseDetection.SupportedModels.BlazePose,
        detectorConfig
      );

      //blazenet configurations end

      setNet(net);
      setLoading(false);
    } catch (error) {
      console.log("Error while loading model", error);
    }
  };

  useEffect(()=>{
    loadPoseNet 
}, [])

  

  return (
    <>
      <div id="pose-detector" style={{ width: 480, height: 352 }}>
        <Webcam
          className="absolute mx-auto left-0 right-0"
          style={{ width: 480, height: 352 }}
          ref={webcamRef}
        />

        <canvas
          className="absolute mx-auto left-0 right-0"
          style={{ width: 480, height: 352 }}
          ref={canvasRef}
        />
      </div>

      
    </>
  );
};

export default VRPoseDetection;
```

### Relevant log output

```shell
Access to fetch at 'https://www.kaggle.com/models/mediapipe/face-detection/frameworks/tfJs/variations/short/versions/1/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/mediapipe/tfjs-model/face_detection/short/1/model.json?tfjs-format=file') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
www.kaggle.com/models/mediapipe/face-detection/frameworks/tfJs/variations/short/versions/1/model.json?tfjs-format=file&tfhub-redirect=true:1 
        
        
       Failed to load resource: net::ERR_FAILED
platform_browser.js:42 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at HTTPRequest.fetch (platform_browser.js:42:16)
    at HTTPRequest.loadModelJSON (http.js:108:47)
    at HTTPRequest.load (http.js:157:38)
    at GraphModel.load (graph_model.js:129:41)
    at loadGraphModel (graph_model.js:554:17)
    at eval (face-detection.esm.js:28:21649)
    at eval (face-detection.esm.js:28:1453)
    at Object.eval [as next] (face-detection.esm.js:28:1558)
    at eval (face-detection.esm.js:28:495)
    at new Promise (<anonymous>)
    at T (face-detection.esm.js:28:240)
    at ee (face-detection.esm.js:28:21014)
    at Module.eval (face-detection.esm.js:28:21933)
    at eval (face-detection.esm.js:28:1453)
    at Object.eval [as next] (face-detection.esm.js:28:1558)
    at eval (face-detection.esm.js:28:495)
    at new Promise (<anonymous>)
    at T (face-detection.esm.js:28:240)
    at Module.te (face-detection.esm.js:28:21777)
    at loadFaceDetectionModel (index.jsx:36:30)
localhost/:1 Access to fetch at 'https://www.kaggle.com/models/mediapipe/face-detection/frameworks/tfJs/variations/short/versions/1/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/mediapipe/tfjs-model/face_detection/short/1/model.json?tfjs-format=file') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
www.kaggle.com/models/mediapipe/face-detection/frameworks/tfJs/variations/short/versions/1/model.json?tfjs-format=file&tfhub-redirect=true:1 
        
        
       Failed to load resource: net::ERR_FAILED
platform_browser.js:42 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
    at HTTPRequest.fetch (platform_browser.js:42:16)
    at HTTPRequest.loadModelJSON (http.js:108:47)
    at HTTPRequest.load (http.js:157:38)
    at GraphModel.load (graph_model.js:129:41)
    at loadGraphModel (graph_model.js:554:17)
    at eval (face-detection.esm.js:28:21649)
    at eval (face-detection.esm.js:28:1453)
    at Object.eval [as next] (face-detection.esm.js:28:1558)
    at eval (face-detection.esm.js:28:495)
    at new Promise (<anonymous>)
    at T (face-detection.esm.js:28:240)
    at ee (face-detection.esm.js:28:21014)
    at Module.eval (face-detection.esm.js:28:21933)
    at eval (face-detection.esm.js:28:1453)
    at Object.eval [as next] (face-detection.esm.js:28:1558)
    at eval (face-detection.esm.js:28:495)
    at new Promise (<anonymous>)
    at T (face-detection.esm.js:28:240)
    at Module.te (face-detection.esm.js:28:21777)
    at loadFaceDetectionModel (index.jsx:36:30)
```

### tensorflow_hub Version

0.12.0 (latest stable release)

### TensorFlow Version

2.8 (latest stable release)

### Python Version

3.x

### OS

Linux

**Comment by HarshJain99** [comment]
I have also been facing the CORS error for the Blazeface model since this morning. I found a [related bug report ](https://github.com/tensorflow/hub/issues/889) from a while ago, which is now closed. Is this also an intermittent issue or are any code updates expected from our end?

**Browser console log **

Access to fetch at 'https://www.kaggle.com/models/tensorflow/blazeface/frameworks/tfJs/variations/default/versions/1/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file') from origin xxxxxxxxxxxxxxxxxxxxxxx has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by KeijiBranshi** [comment]
Hi all, we're looking into this issue. Thanks for your patience.

**Comment by KeijiBranshi** [comment]
Hi all. We rolled out a fix. But please keep up posted if you see this again.

More info here: https://github.com/tensorflow/hub/issues/908#issuecomment-2046026055

Thanks!

**Comment by sourav-5exceptions** [comment]
Thanks @KeijiBranshi, the issue is now resolved.

**Comment by gawrilko** [comment]
Hi,
Looks like the issue is there again:
Access to fetch at 'https://www.kaggle.com/models/mediapipe/blazepose-3d/tfJs/landmark-full/2/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/mediapipe/tfjs-model/blazepose_3d/landmark/full/2/model.json?tfjs-format=file') from origin 'https://localhost:5175' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by baig214** [comment]
Hi ,
Looks like issue is there again.

Access to fetch at 'https://www.kaggle.com/models/mediapipe/face-landmarks-detection/tfJs/attention-mesh/1/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/mediapipe/tfjs-model/face_landmarks_detection/attention_mesh/1/model.json?tfjs-format=file') from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
